### ISSUE TITLE
java.lang.ClassNotFoundException: school.service.AccounService

### ISSUE THREAD

**Issue by ishepherd** [neo4j-examples/neo4j-ogm-university#8]
Hi Luanne, I get this when visiting http://localhost:5050/
'AccounService' seems like a simple typo, but that text does not exist anywhere in the repo so... ??

```
> ./gradlew run
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:prepareBaseDir UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:configureRun
:run
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/ishepher/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.12/42db62298b899818ff17352cbc00050e940bbfb0/slf4j-simple-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/ishepher/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.3/d90276fff414f06cb375f2057f6778cd63c6082f/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[main] INFO ratpack.server.RatpackServer - Ratpack started for http://localhost:5050
[ratpack-compute-1-6] ERROR ratpack.error.internal.DefaultDevelopmentErrorHandler - exception thrown for request to /api/account?cacheBuster=1465816119311
java.lang.ClassNotFoundException: school.service.AccounService
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:676)
        at groovy.lang.GroovyClassLoader$InnerLoader.loadClass(GroovyClassLoader.java:424)
        at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:786)
        at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:774)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at ratpack.getTheService(ratpack.groovy:189)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:382)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:807)
        at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:44)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:444)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:369)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:807)
        at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:44)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:444)
        at org.codehauy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:369)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:151)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at ratpack$_run_closure1$_closure3$_closure14.doCall(ratpack.groovy:169)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)
        at ratpack.groovy.internal.ClosureInvoker.invoke(ClosureInvoker.java:59)
        at ratpack.groovy.handling.internal.ClosureBackedHandler.handle(ClosureBackedHandler.java:42)
        at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:247)
        at ratpack.handling.internal.DefaultContext.insert(DefaultContext.java:278)
        at ratpack.path.internal.PathHandler.handle(PathHandler.java:90)
        at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:247)
        at ratpack.path.internal.PathHandler.handle(PathHandler.java:92)
        at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:247)
        at ratpack.ternal.PathHandler.handle(PathHandler.java:92)
        at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:247)
        at ratpack.path.internal.PathHandler.handle(PathHandler.java:92)
        at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:247)
        at ratpack.path.internal.PathHandler.handle(PathHandler.java:92)
        at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:247)
        at ratpack.path.internal.PathHandler.handle(PathHandler.java:92)
        at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:247)
        at ratpack.path.internal.PathHandler.handle(PathHandler.java:92)
        at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:247)
        at ratpack.path.internal.PathHandler.handle(PathHandler.java:92)
        at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:247)
        at ratpack.path.internal.PathHandler.handle(PathHandler.java:92)
        at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:247)
        at ratpack.path.internal.PathHandler.handle(PathHandler.java:92)
        at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:247)
        at ratpack.path.internal.PathHandler.handle(PathHandler.java:92)
        at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:247)
        at ratpack.handling.internal.DefaultContext.lambda$start$174(DefaultContext.java:157)
        at ratpack.handling.internal.DefaultContext$$Lambda$189/1098333178.execute(Unknown Source)
        at ratpack.exec.internal.ExecutionBacking.lambda$new$108(ExecutionBacking.java:77)
        at ratpack.exec.internal.ExecutionBacking$$Lambda$105/862540116.execute(Unknown Source)
        at ratpack.exec.internal.ExecutionBacking.intercept(ExecutionBacking.java:279)
        at ratpack.exec.internal.ExecutionBacking.intercept(ExecutionBacking.java:246)
        at ratpack.exec.internal.ExecutionBacking.drain(ExecutionBacking.java:215)
        at ratpack.exec.internal.ExecutionBacking.<init>(ExecutionBacking.java:84)
        at ratpack.exec.internal.DefaultExecControl$1.lambda$start$119(DefaultExecControl.java:128)
        at ratec.internal.DefaultExecControl$1$$Lambda$190/212688069.create(Unknown Source)
        at ratpack.util.Exceptions.uncheck(Exceptions.java:103)
        at ratpack.exec.internal.DefaultExecControl$1.start(DefaultExecControl.java:128)
        at ratpack.handling.internal.DefaultContext.start(DefaultContext.java:157)
        at ratpack.server.internal.NettyHandlerAdapter.channelRead0(NettyHandlerAdapter.java:129)
        at ratpack.server.internal.NettyHandlerAdapter.channelRead0(NettyHandlerAdapter.java:54)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at ratpack.server.internal.NettyHandlerAdapter.channelRead(NettyHandlerAdapter.java:91)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker$7.run(DefaultChannelHandlerInvoker.java:158)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:322)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
        at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$136(DefaultExecController.java:84)
        at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory$$Lambda$104/95369743.run(Unknown Source)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ishepherd** [comment]
Re `/api/account?cacheBuster=1465816119311` which is returning this error

I see the references to `api/account` in the Javascript.

_Edit (Spring noob)_ My guess is that the typo is Spring's fault,
`api/account*s*` ==would be==> AccountService.
But it's `api/account` ==so==> AccounService.

But there is is no such bean by either name.

**Comment by luanne** [comment]
@ishepherd you can safely ignore this one. It should've been removed- was never used. There are some scripts referencing it (account.service.js for example), but it really does nothing. Keeping this issue open till we get rid of it altogether.

**Comment by ishepherd** [comment]
@luanne Oh - thanks.
I saw this error + a great missing space on Home tab. So I thought something important was failing.
So this screen looks ok?

![image](https://cloud.githubusercontent.com/assets/3198421/16079757/7e356740-3348-11e6-989c-e754e2513f38.png)

**Comment by luanne** [comment]
Yes, that's how it looks :-)

**Comment by mangrish** [comment]
Fixed this error from occurring on `master`
